/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mochamad Fikri Fadila Akbar - 10117198
 */
public class kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form kalkulator
     */
    public kalkulator() {
        initComponents();
    }
    
    String bilangan;
    double jumlah,bil1,bil2;
    int pilih;
    String temp="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        angka_0 = new javax.swing.JButton();
        op_titik = new javax.swing.JButton();
        op_samadengan = new javax.swing.JButton();
        angka_1 = new javax.swing.JButton();
        angka_2 = new javax.swing.JButton();
        angka_3 = new javax.swing.JButton();
        op_tambah = new javax.swing.JButton();
        op_kali = new javax.swing.JButton();
        op_bagi = new javax.swing.JButton();
        op_kurang = new javax.swing.JButton();
        angka_4 = new javax.swing.JButton();
        anaka_6 = new javax.swing.JButton();
        angka_5 = new javax.swing.JButton();
        angka_7 = new javax.swing.JButton();
        angka_9 = new javax.swing.JButton();
        angka_8 = new javax.swing.JButton();
        op_c = new javax.swing.JButton();
        hasil = new javax.swing.JTextField();
        operasi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 10)); // NOI18N
        jLabel1.setText("- Dibuat Oleh Mochamad Fikri Fadila Akbar - 10117198 -");

        angka_0.setText("0");
        angka_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_0ActionPerformed(evt);
            }
        });

        op_titik.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        op_titik.setText(".");
        op_titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_titikActionPerformed(evt);
            }
        });

        op_samadengan.setBackground(new java.awt.Color(230, 126, 34));
        op_samadengan.setForeground(new java.awt.Color(253, 254, 254));
        op_samadengan.setText("=");
        op_samadengan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_samadenganActionPerformed(evt);
            }
        });

        angka_1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_1.setText("1");
        angka_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_1ActionPerformed(evt);
            }
        });

        angka_2.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_2.setText("2");
        angka_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_2ActionPerformed(evt);
            }
        });

        angka_3.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_3.setText("3");
        angka_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_3ActionPerformed(evt);
            }
        });

        op_tambah.setBackground(new java.awt.Color(230, 126, 34));
        op_tambah.setForeground(new java.awt.Color(253, 254, 254));
        op_tambah.setText("+");
        op_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_tambahActionPerformed(evt);
            }
        });

        op_kali.setBackground(new java.awt.Color(230, 126, 34));
        op_kali.setForeground(new java.awt.Color(253, 254, 254));
        op_kali.setText("X");
        op_kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_kaliActionPerformed(evt);
            }
        });

        op_bagi.setBackground(new java.awt.Color(230, 126, 34));
        op_bagi.setForeground(new java.awt.Color(253, 254, 254));
        op_bagi.setText("/");
        op_bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_bagiActionPerformed(evt);
            }
        });

        op_kurang.setBackground(new java.awt.Color(230, 126, 34));
        op_kurang.setForeground(new java.awt.Color(253, 254, 254));
        op_kurang.setText("-");
        op_kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_kurangActionPerformed(evt);
            }
        });

        angka_4.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_4.setText("4");
        angka_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_4ActionPerformed(evt);
            }
        });

        anaka_6.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        anaka_6.setText("6");
        anaka_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anaka_6ActionPerformed(evt);
            }
        });

        angka_5.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_5.setText("5");
        angka_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_5ActionPerformed(evt);
            }
        });

        angka_7.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_7.setText("7");
        angka_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_7ActionPerformed(evt);
            }
        });

        angka_9.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_9.setText("9");
        angka_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_9ActionPerformed(evt);
            }
        });

        angka_8.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        angka_8.setText("8");
        angka_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angka_8ActionPerformed(evt);
            }
        });

        op_c.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        op_c.setText("C");
        op_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                op_cActionPerformed(evt);
            }
        });

        hasil.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(angka_1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(angka_2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(angka_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(op_titik, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(angka_3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka_4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka_5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anaka_6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(angka_7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka_8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(angka_9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(op_c, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(op_samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_kali, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(op_bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(operasi)
                        .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(operasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(op_bagi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(op_c, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(op_kali, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(op_kurang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(angka_4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(angka_5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(anaka_6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(angka_1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(angka_2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(angka_3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(op_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angka_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(op_titik, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(op_samadengan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(angka_7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(angka_8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(angka_9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        angka_0.getAccessibleContext().setAccessibleName("angka_nol");
        op_titik.getAccessibleContext().setAccessibleName("op_titik");
        op_samadengan.getAccessibleContext().setAccessibleName("op_samadengan");
        angka_1.getAccessibleContext().setAccessibleName("angka_1");
        angka_2.getAccessibleContext().setAccessibleName("angka_2");
        angka_2.getAccessibleContext().setAccessibleDescription("");
        angka_3.getAccessibleContext().setAccessibleName("angka_3");
        angka_3.getAccessibleContext().setAccessibleDescription("");
        op_tambah.getAccessibleContext().setAccessibleName("op_tambah");
        op_kali.getAccessibleContext().setAccessibleName("op_kali");
        op_bagi.getAccessibleContext().setAccessibleName("op_bagi");
        op_kurang.getAccessibleContext().setAccessibleName("op_kurang");
        angka_4.getAccessibleContext().setAccessibleName("angka_4");
        anaka_6.getAccessibleContext().setAccessibleName("angka_6");
        angka_5.getAccessibleContext().setAccessibleName("angka_5");
        angka_7.getAccessibleContext().setAccessibleName("angka_7");
        angka_9.getAccessibleContext().setAccessibleName("angka_9");
        angka_8.getAccessibleContext().setAccessibleName("angka_8");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void op_titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_titikActionPerformed
        // TODO add your handling code here:    
        bilangan =".";        
        hasil.setText(hasil.getText()+bilangan);
    }//GEN-LAST:event_op_titikActionPerformed

    private void op_samadenganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_samadenganActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            bil2 = Double.parseDouble(String.valueOf(bilangan));
            jumlah = bil1/bil2;
            bilangan = Double.toString(jumlah);            
            break;
        case 2:
            bil2 =Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah = bil1 * bil2;
            bilangan = Double.toString(jumlah);            
            break;
        case 3:
            bil2 = Double.valueOf(bilangan);
            jumlah = bil1 + bil2;
            bilangan = String.valueOf(jumlah);            
            break;
        case 4:
            bil2 = Double.parseDouble(String.valueOf(hasil.getText()));
            jumlah = bil1 - bil2;
            bilangan = Double.toString(jumlah);            
            break;            
        } 
        operasi.setText(operasi.getText()+" = "+ bilangan);
        hasil.setText(bilangan);
    }//GEN-LAST:event_op_samadenganActionPerformed

    private void angka_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_0ActionPerformed
        // TODO add your handling code here:
        bilangan = hasil.getText()+"0";        
        hasil.setText(bilangan);
    }//GEN-LAST:event_angka_0ActionPerformed

    private void angka_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_1ActionPerformed
        // TODO add your handling code here:
        bilangan = temp + "1";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "1");
    }//GEN-LAST:event_angka_1ActionPerformed

    private void angka_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_2ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"2";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "2");
    }//GEN-LAST:event_angka_2ActionPerformed

    private void angka_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_3ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"3";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "3");
    }//GEN-LAST:event_angka_3ActionPerformed

    private void op_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_tambahActionPerformed
        // TODO add your handling code here:
        bil1  = Double.valueOf(bilangan);
        pilih = 3;       
        bilangan = "";
        operasi.setText(hasil.getText() + "+");     
        
    }//GEN-LAST:event_op_tambahActionPerformed

    private void op_kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_kaliActionPerformed
        // TODO add your handling code here:
        
        bil1  = Double.valueOf(bilangan);
        pilih = 2;       
        bilangan = "";
        operasi.setText(hasil.getText() + "*");     
    }//GEN-LAST:event_op_kaliActionPerformed

    private void op_bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_bagiActionPerformed
        // TODO add your handling code here:
        
        bil1  = Double.valueOf(bilangan);
        pilih = 1;       
        bilangan = "";
        operasi.setText(hasil.getText() + "/");     
    }//GEN-LAST:event_op_bagiActionPerformed

    private void op_kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_kurangActionPerformed
        // TODO add your handling code here:
        
        bil1  = Double.valueOf(bilangan);
        pilih = 4;       
        bilangan = "";
        operasi.setText(hasil.getText() + "-");            
    }//GEN-LAST:event_op_kurangActionPerformed

    private void angka_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_4ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"4";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "4");
    }//GEN-LAST:event_angka_4ActionPerformed

    private void anaka_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anaka_6ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"6";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "6");
    }//GEN-LAST:event_anaka_6ActionPerformed

    private void angka_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_5ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"5";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "5");
    }//GEN-LAST:event_angka_5ActionPerformed

    private void angka_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_7ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"7";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "7");
    }//GEN-LAST:event_angka_7ActionPerformed

    private void angka_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_9ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"9";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "9");
    }//GEN-LAST:event_angka_9ActionPerformed

    private void angka_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angka_8ActionPerformed
        // TODO add your handling code here:
        bilangan = temp+"8";        
        hasil.setText(bilangan);
        operasi.setText(operasi.getText() + "8");
    }//GEN-LAST:event_angka_8ActionPerformed

    private void op_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_op_cActionPerformed
        // TODO add your handling code here:        
        hasil.setText("");
        operasi.setText("");
        bil1=0.0;
        bil2=0.0;
        jumlah=0.0;
        bilangan="";
    }//GEN-LAST:event_op_cActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anaka_6;
    private javax.swing.JButton angka_0;
    private javax.swing.JButton angka_1;
    private javax.swing.JButton angka_2;
    private javax.swing.JButton angka_3;
    private javax.swing.JButton angka_4;
    private javax.swing.JButton angka_5;
    private javax.swing.JButton angka_7;
    private javax.swing.JButton angka_8;
    private javax.swing.JButton angka_9;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton op_bagi;
    private javax.swing.JButton op_c;
    private javax.swing.JButton op_kali;
    private javax.swing.JButton op_kurang;
    private javax.swing.JButton op_samadengan;
    private javax.swing.JButton op_tambah;
    private javax.swing.JButton op_titik;
    private javax.swing.JLabel operasi;
    // End of variables declaration//GEN-END:variables
}
